[package]
name = "sniprun"
version = "0.5.2"
authors = ["michaelb <michael.bleuez2@gmail.com>"]
edition = "2018"

[features]
ignore_in_ci = []
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
# cc="*"

[dependencies]
neovim-lib="0.6.1"
log="0.4.14"
simple-logging="2.0.2"
thiserror="1.0.24"
dirs="3.0.1"
regex="1.4.5"
serde_json="1.0.64"
strip-ansi-escapes="0.1.0"

jupyter-client="0.1.0"

# tree-sitter stuff
# tree-sitter = "0.16.1"

# Python3 interpreter
unindent="0.1.7"
