name: Rust

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name : build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --release

  unittest:
    name: unit tests
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Unit tests
      run: cargo test --release -- --test-threads=1


  e2etests:
    name: end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - name: install vroom
        run: git clone https://github.com/google/vroom && cd vroom && python3 setup.py build && sudo python3 setup.py install && cd .. && python3 -m pip install -U neovim neovim-remote
      - uses: actions/checkout@v2
      - name: run vroom tests
        run : vroom --crawl --neovim -u plugin/sniprun.vim

  install:
    name: install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Installation tests
      run: ./install.sh

  codecov:
    name : codecov
    runs-on: ubuntu-latest
    steps:
    - name : allow add cargo to path
      run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Code coverage
      uses: actions-rs/tarpaulin@v0.1.0
      with:
        args: '-- --test-threads=1'

    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1.0.2
      with:
          token: ${{secrets.CODECOV_TOKEN}}


