name: Rust

on:
  push:
    branches: [ master, dev]
  pull_request:
    branches: [ master, dev]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name : build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --release

  unittest:
    name: unit tests
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: install all compilers
      run: sudo apt install haskell-platform -y &&
          sudo apt install -y nodejs npm &&
          sudo npm install -g coffee-script &&
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9 && 
          sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/' &&
          sudo apt install r-base &&
          sudo apt install gnat &&
          sudo apt install scala &&
          pip3 install jupyter &&
          sudo apt install lua5.3 &&
          ./ressources/go_install.sh &&
          export PATH=$PATH:$HOME/golang/go/bin/

    - uses: dlang-community/setup-dlang@v1



    - name: Unit tests
      run: cargo test --features ignore_in_ci




  install:
    name: install (download)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Installation tests
      run: ./install.sh


 

  codecov:
    name : codecov
    runs-on: ubuntu-latest
    steps:
    - name : allow add cargo to path
      run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: install all fking compilers
      run: sudo apt install haskell-platform -y &&
          sudo apt install -y nodejs npm &&
          sudo npm install -g coffee-script &&
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9 && 
          sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/' &&
          sudo apt install r-base &&
          sudo apt install gnat &&
          sudo apt install scala &&
          pip3 install jupyter &&
          sudo apt install lua5.3 &&
          ./ressources/go_install.sh &&
          export PATH=$PATH:$HOME/golang/go/bin/

    - uses: dlang-community/setup-dlang@v1


   

    - name: Code coverage
      uses: actions-rs/tarpaulin@v0.1.0
      with:
        args: --features ignore_in_ci -- --test-threads=1

    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1.0.2
      with:
          token: ${{secrets.CODECOV_TOKEN}}


